name: Sync test

on:
  workflow_run:
    workflows: 
     - Builds 
     - Build examples - Mbed OS
    types: 
      - completed

jobs:
    test_sync:
        runs-on: ubuntu-latest

        name: test_sync

        steps:
          - uses: ahmadnassri/action-workflow-run-wait@v1
          - name: Send some dummy message
            run: echo test message