name: Sync test

on:
  workflow_run:
    workflows: 
     - "Builds" 
     - "Build examples - Mbed OS"
    types: 
      - requested
      - completed

jobs:
    test_sync:
        runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@v2
          - uses: ahmadnassri/action-workflow-run-wait@v1
          
          - name: Download CHIP-app linux artifacts
            uses: dawidd6/action-download-artifact@v2
            with:
              workflow: build.yaml
              workflow_conclusion: success
              path: build_artifacts

          - name: Download test target artifacts
            uses: dawidd6/action-download-artifact@v2
            with:
              workflow: examples-mbed.yaml
              workflow_conclusion: success
              path: examples_mbed_artifacts