name: Sync test

on:
  push:

jobs:
  sync_test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup configuration
        run: |
              set -x
              sudo apt-get update
              sudo apt install jq -fy

      - name: Check for chip-tools run id
        run: |
              echo "CHIP_TOOL_RUN_ID=$(\
              curl --silent \
              --request GET \
              --url 'https://api.github.com/repos/${{ github.repository }}/actions/workflows/build_cr.yaml/runs?per_page=1&status=success' \
              --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
              --header 'content-type: application/json' | \
              jq '.workflow_runs[0].id' \
              )" \
              >> $GITHUB_ENV

      
      - name: additional verification step
        run: |
              if [[ "$CHIP_TOOL_RUN_ID" == "null" ]]; then
              echo "::error::Can't obtain last succesfull run_id from build_cr.yaml workflow"
              exit 1
              fi

      - name: Display received result
        run: |
              echo "$CHIP_TOOL_RUN_ID"